import type { Metadata } from "next";
import { CiHeart } from "react-icons/ci";
import { IoIosSearch, IoMdHome } from "react-icons/io";
import { RiUser3Line } from "react-icons/ri";
export const metadata: Metadata = {
    title: "Home",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <section className="  flex flex-row bg-slate-200 ">
            <div className=" w-18 rounded-r-3xl h-auto bg-blue-600 ">
                <div className="h-1/4 hover:bg-slate-400  ml-3  mr-3 hover:rounded-lg flex ">
                    <div className="relative h-1/2 w-full my-auto ">
                        <IoMdHome className="text-4xl text-white" />  
                        <div className=" text-xs text-white flex place-content-center">HOME</div> 
                    </div>
                </div>
                <div className="h-1/4 hover:bg-slate-400  ml-3  mr-3 hover:rounded-lg flex ">
                    <div className="relative h-1/2 w-full my-auto ">
                        <IoIosSearch className="text-4xl text-white " />
                        <div className=" text-xs text-white flex place-content-center">Explore</div> 
                    </div>
                </div>
                <div className="h-1/4 hover:bg-slate-400  ml-3  mr-3 hover:rounded-lg flex ">
                    <div className="relative h-1/2 w-full  my-auto">
                    <CiHeart  className="text-4xl text-white" />
                        <div className=" text-xs text-white flex place-content-center">Trip</div> 
                    </div>
                </div>
                <div className="h-1/4 hover:bg-slate-400 ml-3  mr-3 hover:rounded-lg flex ">
                    <div className="relative h-1/2 w-full  my-auto ">
                    <RiUser3Line   className="text-4xl text-white  " />
                        <div className=" text-xs text-white">HOME</div> 
                    </div>
                </div>
                
            </div>
            <div className="static w-[100px] h-full  bg-slate-200 flex-1">
                {children}
            </div>
        </section>
    );
}
